language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
sudo: required

matrix:
  include:
    # https://docs.travis-ci.com/user/reference/osx/#os-x-version
    - os: osx # 10.13
      osx_image: xcode10
    - os: osx # 10.13
      osx_image: xcode9.4

branches:
  only:
    - master

before_install:
  - sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev

install:
  - npm install

before_script:
  - npm run lint
