language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
sudo: required
dist: trusty


branches:
  only:
    - master

before_install:
  - sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev

install:
  - npm install

before_script:
  - npm run lint
