sudo: required
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
matrix:
  fast_finish: true
  include:
    - os: linux
      env: HOST_OS=linux
    - os: osx
      env: HOST_OS=osx

branches:
  only:
    - master

before_install:

  - if [ ${HOST_OS} = "linux" ]; then sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev; fi

install:
  - npm install

before_script:
  - npm run lint
