sudo: required
language: node_js

notifications:
  email: true

matrix:
  fast_finish: true
  include:
    #################
    # Ubuntu Trusty #
    #################

    - name: '[Trusty] Node.js v6.x'
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev
      node_js: '6'

    - name: '[Trusty] Node.js v8.x'
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev
      node_js: '8'

    # Not supported until bluetooth-hci-socket supports node 10
    # https://github.com/noble/node-bluetooth-hci-socket/pull/91
    # - name: "[Trusty] Node.js v10.x"
    #   sudo: required
    #   dist: trusty
    #   before_install:
    #     - sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev
    #   node_js: "10"

    ########
    # OS X #
    ########

    - name: '[OSX] Node.js v6.x'
      os: osx
      osx_image: xcode9.3
      node_js: '6'

    - name: '[OSX] Node.js v8.x'
      os: osx
      osx_image: xcode9.3
      node_js: '8'

    - name: '[OSX] Node.js v10.x xcode` 9.3'
      os: osx
      osx_image: xcode9.3
      node_js: '10'

    - name: '[OSX] Node.js v10.x xcode10'
      os: osx
      osx_image: xcode10
      node_js: '10'
      script:
        - npm run build
        - npm run report-coverage
      after_success:
        - semantic-release

branches:
  only:
    - master

install:
  - npm install

before_script:
  - npm run lint

script:
  - echo "begin scripts"
  - npm run build
  - npm run report-coverage
